# Модуль 18. NLP. Практика
## Занятие 1. Задания
### Общая информация

#### Цель заданий

* Освоить базовый синтаксис регулярных выражений.
* Научиться применять регулярные выражения в разных задачах анализа данных.
* Научиться применять регулярные выражения совместно с библиотекой Pandas.

Задания не нужно сдавать на проверку: обязательных и необязательных задач нет, все они факультативные. Однако мы рекомендуем решить их, чтобы потренироваться.

К занятию приложен файл `captions_csv2.csv` с подписями к фотографиям в одной `социальной сети`. Скачайте его на компьютер. 


### Задача 1
В подписях к фотографиям из файла `captions_csv2.csv` найдите топ-10 тегов, которые встречаются чаще всего. 
#### Советы и рекомендации
##### Шаг 1
Считайте файл `captions_csv2.csv` в Pandas-dataframe `df`.
##### Шаг 2
Содайте в `df` новую колонку `tag`, запишите в неё массивы тегов из соответствующих значений колонки `caption`. Для этого используйте функцию [apply](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html), передав в неё в качестве аргумента соответствующую функцию из пакета стандартной библиотеки Python [re](https://docs.python.org/3/library/re.html). 
##### Шаг 3
Теперь в колонке `tag` вашего датафрейма содержатся массивы тегов, которые вы «извлекли» из текстов с описаниями. Примерно так:

|id|tag|
|--|---|
|20516|[#stayhomeclub]|
|20517|[#KatyPursey, #StayHome, #ShoesdayTuesday]|
|20518|[]|
|...|...|

Вам нужно «распаковать» массивы тегов так, чтобы каждое значение колонки `tag` содержало только один тег. Другими словами, преобразовать датафрейм в следующий вид:

|id|tag|
|--|---|
|20516|#stayhomeclub|
|20517|#KatyPursey|
|20517|#StayHome|
|20517|#ShoesdayTuesday|
|...|...|

Это можно сделать по-разному. Мы рекомендуем использовать Pandas-функцию [explode](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html) (и не забудьте удалить строки со значениями NaN). Сохраните «распакованные» данные в новый датафрейм `id2tag` (вам понадобятся только колонки `id` и `tag`). Кстати, такую «распаковку» массивов можно рассматривать как приведение отношения [к первой нормальной форме](https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B2%D0%B0%D1%8F_%D0%BD%D0%BE%D1%80%D0%BC%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%84%D0%BE%D1%80%D0%BC%D0%B0).
##### Шаг 4
Найдите топ-10 тегов, которые встречаются чаще всего.

In [ ]:
import re

import pandas as pd

#
# Ваш код здесь
#

### Задача 2

Найдите номер (id) подписи, которая содержит максимальное количество тегов. Выведите соответствующую подпись на экран. Используйте датафрейм `id2tag`, созданный в предыдущей задаче.

In [ ]:
#
# Ваш код здесь
#

### Задача 3

На основе датафрейма `id2tag` создайте новый датафрейм, в который войдут все строки `id2tag`. В значениях `tag` этих строк должны содержаться теги, начинающиеся и заканчивающиеся цифрой (для проверки этого свойства используйте регулярное выражение).  
#### Рекомендации по выполнению
##### Шаг 1
Создайте функцию `regex_filter`, которая принимает единственный аргумент – тег и возвращает `True`, если тег соответствует шаблону (начинается и заканчивается цифрой),  и `False` – в противном случае.
##### Шаг 2
Для колонки `tag` датафрейма `id2tag` вызовите функцию [apply](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html), в качестве аргумента которой передайте функцию `regex_filter`.
##### Шаг 3
Используйте pandas-series, состоящий из `True`/`False`, который получен на предыдущем шаге, в качестве фильтра в датафрейме `id2tag`.

### Задача 4
Кроме тегов, в подписях встречается другая конструкция: имена пользователей. Имя пользователя похоже на тег, но в отличие от него предваряется символом `собачка` (`@`), а не решёткой. В одной подписи может быть несколько тегов и несколько имён пользователей, могут быть только теги или имена пользователей, а может не быть ни того ни другого. В задаче 4 вам нужно выполнить следующее:  
1. Найти тег, с которым употребляется максимальное количество имён пользователей (во всех подписях датасета). Другими словами: взять тег, найти все подписи, в которых он встречается, и посчитать, сколько уникальных имен пользователей содержат `все` эти подписи. Вы получите количество пользователей, которые встречались в подписях в паре с этим тегом. Проделайте эту операцию для всех тегов, потом выберите тот, который встречался в паре с максимальным количеством пользователей. 
1. Обратная задача: найти имя пользователя, которое встречалось в паре с максимальным количеством уникальных тегов (во всех подписях датасета).
1. Взять имя пользователя, которое вы нашли на предыдущем шаге, и вывести топ-10 тегов (по частоте встречаемости), которые встречались в паре с этим именем пользователя.
#### Советы и рекомендации
Теги и имена пользователей в подписях образуют отношение «многие ко многим», и вам нужно выполнить несколько «запросов» в это отношение. Это можно сделать разными способами, одним из наиболее удобных видится описанный ниже.  
##### Шаг 1
Создайте датафрейм `id2user` по аналогии с тем, как создавали датафрейм `id2tag`. Первым столбцом в этом датафрейме должен быть идентификатор подписи, а вторым – имя пользователя (для его извлечения используйте регулярное выражение), которое встречалось в подписи с соответствующим идентификатором. Идентификаторы подписей могут повторяться, указывая на то, что соответствующая подпись включает несколько имён пользователей.
##### Шаг 2
Создайте датафрейм `full_df`, который представляет собой `inner join` датафреймов `id2tag` и `id2user` по колонке `id`. Воспользуйтесь функцией [pandas merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html). Таким образом, каждая строка `full_df` будет состоять из идентификатора подписи и пары {тег, имя пользователя}, которые встречались вместе в этой подписи.
##### Шаг 3
Используя функции Pandas, выполните подзадачу 1.
##### Шаг 4
Используя функции Pandas, выполните подзадачу 2.
##### Шаг 5
Используя функции Pandas, выполните подзадачу 3.

In [ ]:
#
# Ваш код здесь
#

## Занятие 1 / Решения

### Задача 1

In [ ]:
import re

import pandas as pd

### ШАГ 1

# Замените путь к файлу captions_csv2.csv на ваш
df = pd.read_csv('data/skillbox/ml_jun18/captions_csv2.csv', names=['id', 'link', 'caption'])

df.head()

      id             link                                            caption
0  20516  img2/insta20516                  wHaT dAy Is It Even #stayhomeclub
1  20517  img2/insta20517  Vitamin C for your fashion diet #KatyPursey #S...
2  20518  img2/insta20518  do you know the hotter the fire the purer the ...
3  20519  img2/insta20519                                   @ryanseacrest 👍🏻
4  20520  img2/insta20520           working hard or hardly working idk 🤷🏼‍♀️

In [ ]:
### ШАГ 2

pattern = re.compile('#\w+')

df['tag'] = df['caption'].apply(pattern.findall)

df.head()

,id,link,caption,tag
0,20516,img2/insta20516,wHaT dAy Is It Even #stayhomeclub,[#stayhomeclub]
1,20517,img2/insta20517,Vitamin C for your fashion diet #KatyPursey #S...,"[#KatyPursey, #StayHome, #ShoesdayTuesday]"
2,20518,img2/insta20518,do you know the hotter the fire the purer the ...,[]
3,20519,img2/insta20519,@ryanseacrest 👍🏻,[]
4,20520,img2/insta20520,working hard or hardly working idk 🤷🏼‍♀️,[]

In [ ]:
### ШАГ 3

id2tag = df.explode('tag')[['id', 'tag']].dropna()

id2tag.head()

      id               tag
0  20516     #stayhomeclub
1  20517       #KatyPursey
1  20517         #StayHome
1  20517  #ShoesdayTuesday
5  20521  #ShoesdayTuesday

In [ ]:
### ШАГ 4

id2tag['tag'].value_counts().head(10)

#StriveForGreatness    154
#Repost                 61
#love                   53
#TBT                    45
#LOVE                   44
#TheBoyNextDoor         40
#shadesofblue           37
#FENTYxPUMA             33
#JLoVegas               33
#repost                 32
Name: tag, dtype: int64

### Задача 2

In [ ]:
id2tag['id'].value_counts().head(1)

29080    17
Name: id, dtype: int64

In [ ]:
df[df['id'] == 29080]['caption']

8564    #feeling#good#after#2months#atlast#i#am#fit#n#...
Name: caption, dtype: object

### Задача 3

In [ ]:
### ШАГ 1
def regex_filter(tag):
    return bool(re.search('#\d+[a-zA-Z]+\d+$', str(tag)))

### ШАГ 2
flt = id2tag['tag'].apply(regex_filter)
    
### ШАГ 3    
id2tag[flt]

          id            tag
8605   29121  #3DaysToSOTY2
9607   30123  #4daystosoty2
13388  33904       #330x216

### Задача 4

In [ ]:
# ШАГ 1

pattern = re.compile('@\w+')

df['user'] = df['caption'].apply(lambda x: pattern.findall(x))

id2user = df.explode('user')[['id', 'user']].dropna()

id2user.head()

      id                   user
1  20517  @katyperrycollections
3  20519          @ryanseacrest
5  20521  @katyperrycollections
6  20522  @katyperrycollections
7  20523            @vogueindia

In [ ]:
# ШАГ 2

full_df = pd.merge(id2tag, id2user, on='id')

full_df.head()

      id                     tag                   user
0  20517             #KatyPursey  @katyperrycollections
1  20517               #StayHome  @katyperrycollections
2  20517        #ShoesdayTuesday  @katyperrycollections
3  20521        #ShoesdayTuesday  @katyperrycollections
4  20522  #ProtectYourEnergy2020  @katyperrycollections

In [ ]:
# ШАГ 3

full_df.groupby('tag')['user'].nunique().sort_values(ascending=False).head(1)

tag
#Repost    59
Name: user, dtype: int64

In [ ]:
# ШАГ 4

full_df.groupby('user')['tag'].nunique().sort_values(ascending=False).head(1)

user
@fentybeauty    52
Name: tag, dtype: int64

In [ ]:
# ШАГ 5

full_df[full_df['user'] == '@gomillionandleupold']['tag'].value_counts().head(10)

#JLoBTS            18
#JLoAKA             9
#Greece             9
#JLoiHeartRadio     7
#Ultimate           6
#PoolParty          6
#JLoPhotos          6
#DownloadJLoAKA     6
#JLoAtFoxWoods      5
#January23          4
Name: tag, dtype: int64